<?php

/**
 * File _config.phtml
 * 
 * @versoin 1.0
 * @author OanhNN
 * 
 * @todo Config view and layout
 */
// Set encoding
$this->setEncoding('UTF-8');

// Set doctype
$this->doctype('XHTML1_STRICT');

// Set meta
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8')
        ->appendHttpEquiv('Content-Language', 'vi-VN');

// Set favicon
$this->headLink(array('rel' => 'shortcut icon', 'href' => 'favicon.ico', 'type' => 'image/x-icon'), 'append');

// Set css style
$this->headLink()->appendStylesheet($this->baseUrl() . '/application/template/' . TEMPLATE_NAME . '/css/style.css', 'all');
// fix css for IE8 or LOWER
$this->headLink()->appendStylesheet($this->baseUrl() . '/application/template/' . TEMPLATE_NAME . '/css/style-ie8.css', 'all', 'lte IE 8');
// Set js script
$this->headScript()->appendFile($this->baseUrl() . '/application/template/' . TEMPLATE_NAME . '/js/custom.js');

// Add view helper
$this->addHelperPath('ZendX/JQuery/View/Helper/', 'ZendX_JQuery_View_Helper');
$this->addHelperPath('Zend/Dojo/View/Helper/', 'Zend_Dojo_View_Helper');
$viewRenderer = new Zend_Controller_Action_Helper_ViewRenderer();
$viewRenderer->setView($this);
Zend_Controller_Action_HelperBroker::addHelper($viewRenderer);

// Config jQuery and jQuery UI
$this->jQuery()->setLocalPath('lib/jquery-ui-1.8.14/js/jquery-1.5.1.min.js')
        ->disable()
        ->uiDisable();

// Set dojo library
Zend_Dojo_View_Helper_Dojo::setUseDeclarative();
$this->dojo()->setDjConfigOption('usePlainJson', TRUE)
        ->setLocalPath('lib/dojo-release-1.6.1/dojo/dojo.js')
        ->addStyleSheetModule('dijit.themes.tundra')
//        ->addStylesheet('lib/dojo-release-1.6.1/dojox/grid/resources/tundraGrid.css')
//        ->addStylesheet('lib/dojo-release-1.6.1/dojox/grid/resources/Grid.css')
        ->disable();
?>
