<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
<form id="form1" name="form1" method="post" action="">
<table width="339" border="1" align="center" cellpadding="2" cellspacing="2">
  <tr>
    <td colspan="2">ID equirments</td>
    <td width="9">:</td>
    <td width="130"><label for="mataisan"></label>
      <input type="text" name="mataisan" id="mataisan" /></td>
  </tr>
  <tr>
    <td colspan="2">Description</td>
    <td>:</td>
    <td><label for="description"></label>
      <input type="text" name="description" id="description" /></td>
  </tr>
  <tr>
    <td colspan="2">type</td>
    <td>:</td>
    <td><label for="type"></label>
      <input type="text" name="type" id="type" /></td>
  </tr>
  <tr>
    <td colspan="2">Start date</td>
    <td>:</td>
    <td><label for="startDate"></label>
      <input type="text" name="startDate" id="startDate" /></td>
  </tr>
  <tr>
    <td colspan="2">Start date converted</td>
    <td>:</td>
    <td><label for="startDateConverted"></label>
      <input type="text" name="startDateConverted" id="startDateConverted" /></td>
  </tr>
  <tr>
    <td colspan="2">Price</td>
    <td>:</td>
    <td><label for="price"></label>
      <input type="text" name="price" id="price" /></td>
  </tr>
  <tr>
    <td colspan="2">Warranty time</td>
    <td>:</td>
    <td><label for="warrantyTime"></label>
      <input type="text" name="warrantyTime" id="warrantyTime" /></td>
  </tr>
  <tr>
    <td colspan="2">Status</td>
    <td>:</td>
    <td><label for="status"></label>
      <input type="text" name="status" id="status" /></td>
  </tr>
  <tr>
    <td colspan="2">Place</td>
    <td>:</td>
    <td><label for="place"></label>
      <input type="text" name="place" id="place" /></td>
  </tr>
  <tr>
    <td ><input type="submit" name="add" id="add" value="Edit" /></td>
    <td ><input type="reset" name="reset" id="reset" value="Reset" /></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    </tr>
</table>
</form>
</body>
</html>