<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
<form action="" method="post">
<table width="50%" border="0" align="center">
	<tr>
		<td colspan="2">User ID</td>
		<td width="4%">:</td>
		<td width="62%"><label for="ownID"></label> <input type="text"
			name="ownID" id="ownID" /></td>
	</tr>
	<tr>
		<td colspan="2">Requirment ID</td>
		<td>:</td>
		<td><label for="maTaiSan"></label> <input type="text"
			name="maTaiSan" id="maTaiSan" /></td>
	</tr>
	<tr>
		<td colspan="2">Type</td>
		<td>:</td>
		<td><label for="type"></label> <input type="text" name="type"
			id="type" /></td>
	</tr>
	<tr>
		<td colspan="2">Detail</td>
		<td>:</td>
		<td><label for="detail"></label> <input type="text" name="detail"
			id="detail" /></td>
	</tr>
	<tr>
		<td colspan="2">Curtime</td>
		<td>:</td>
		<td><label for="y-m-d"></label> <input type="text" name="y-m-d"
			id="y-m-d" /></td>
	</tr>
	<tr>
		<td width="18%"><input type="submit" name="add" id="add"
			value="Add" /></td>
		<td width="18%"><input type="reset" name="reset" id="reset"
			value="Reset" /></td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
</table>
</form>
</body>
</html>