<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
<table width="200" border="1" align="center">
	<tr>
		<td>Start date</td>
		<td>:</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td>End date</td>
		<td>:</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td>Item ID</td>
		<td>:</td>
		<td>&nbsp;</td>
	</tr>
</table>
</body>
</html>