<?php $imagesDir = $this->baseUrl() . '/templates/default/images/'; ?>
<table width="100%">
    <tbody>
        <tr>
            <td height="100%">
                <div align="center">
                    <div class="log">
                        <div id="textbox">
                            <script type="text/javascript">
                                <!--
                                if (document.getElementById('txtkeyword').value!='')
                                    document.getElementById('qs_txt').value=document.getElementById('txtkeyword').value;
                                -->
                            </script>

                            <form class="txt" id="txt" action="<?php echo $this->url(array('module' => 'front', 'controller' => 'auth', 'action' => 'login')); ?>" method="post">
                                <p>
                                    <input class="qs_txt" id="txtUsername" name="txtUsername" type="text" 
                                           onblur="if (this.value=='') this.value='Username';"
                                           onfocus="if (this.value=='Username') this.value='';" 
                                           value="Username"/>
                                </p>
                                <p>
                                    <input class="qs_txt" id="txtPassword" name="txtPassword" type="password" 
                                           onblur="if (this.value=='') this.value='Password';" 
                                           onfocus="if (this.value=='Password') this.value='';" 
                                           value="Password"/>
                                </p>
                                <br/>
                                <br/>
                                <p>
                                    <input type="image" onmouseover="this.src='<?php echo $imagesDir . 'btn_submit_hover.png' ?>';" 
                                           onmouseout="this.src='<?php echo $imagesDir . 'btn_submit.png'; ?>';"  
                                           style="border: medium none ;" src='<?php echo $imagesDir . 'btn_submit.png'; ?>' 
                                           alt="Login" title="Login"/>
                                </p>
                            </form>
                        </div>
                    </div>
                    <p style="color:#fff">
        	GROUP 01 © HEDSPI-INTERNSHIP2011.
                    </p>
                </div>
            </td>
        </tr>
    </tbody>
</table>    