<?php include_once 'html/_config.phtml'; ?>
<?php echo $this->doctype() . PHP_EOL; ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php
        echo $this->headTitle() . PHP_EOL;
        echo $this->headMeta() . PHP_EOL;
        echo $this->headLink() . PHP_EOL;
        echo $this->headStyle() . PHP_EOL;
        echo $this->headScript() . PHP_EOL;
        if ($this->dojo()->isEnabled()) {
            echo $this->dojo() . PHP_EOL;
        }
        if ($this->jQuery()->isEnabled()) {
            if ($this->jQuery()->uiIsEnabled()) {
                $this->jQuery()->setUiLocalPath('lib/jquery-ui-1.8.14/js/jquery-ui-1.8.14.custom.min.js')
                        ->addStylesheet('lib/jquery-ui-1.8.14/css/pepper-grinder/jquery-ui-1.8.14.custom.css');
            }
            echo $this->jQuery() . PHP_EOL;
        }
        ?>      
    </head>
    <body class="tundra">
        <div id="wapper">
            <div id="banner">
                <?php echo $this->render('html/_banner.phtml') . PHP_EOL; ?>
            </div>
            <div id="content">
                <?php echo $this->layout()->content . PHP_EOL; ?>
            </div>
            <div id="footer">
                <?php echo $this->render('html/_footer.phtml') . PHP_EOL; ?>
            </div>
        </div>
    </body>
</html>
