<?php include_once 'html/_config.phtml'; ?>
<?php echo $this->doctype() . PHP_EOL; ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->headTitle() . PHP_EOL; ?>
        <?php echo $this->headMeta() . PHP_EOL; ?>
        <?php echo $this->headLink() . PHP_EOL; ?>
        <?php echo $this->headStyle() . PHP_EOL; ?>
        <?php echo $this->headScript() . PHP_EOL; ?>   
    </head>
    <body>
        <div id="wapper">
            <div id="banner"><?php include_once 'html/_banner.phtml'; ?></div>
            <div id="content"><?php echo $this->layout()->content . PHP_EOL; ?></div>
            <div id="footer"><?php include_once 'html/_footer.phtml'; ?></div>
        </div>
    </body>
</html>
