<?php
/**
 * File layout.phtml
 * 
 * @versoin 1.0
 * @author OanhNN
 * 
 * @todo layout of application
 */
// Set encoding
$this->setEncoding('UTF-8');

// Set doctype
$this->doctype('XHTML1_STRICT');

// Set meta
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
$this->headMeta()->appendHttpEquiv('Content-Language', 'vi-VN');

// Set title
$this->headTitle()->append($this->translate('PAGE_TITLE'));
$this->headTitle()->setSeparator(' :: ');
$this->headTitle()->append($this->pagetitle);

// Set favicon
$this->headLink(array('rel' => 'shortcut icon', 'href' => 'favicon.ico', 'type' => 'image/x-icon'), 'append');

// Set css style
$this->headLink()->appendStylesheet($this->baseUrl() . '/application/template/' . TEMPLATE_NAME . '/css/style.css', 'screen');
// fix css for IE8 or LOWER
$this->headLink()->appendStylesheet($this->baseUrl() . '/application/template/' . TEMPLATE_NAME . '/css/style-ie8.css', 'screen', 'lte IE 8');

// Set js script
$this->headScript()->appendFile($this->baseUrl() . 'lib/jquery-ui-1.8.14/js/jquery-1.5.1.min.js');


// Config jQuery and jQuery UI
//ZendX_JQuery::enableView($this);
//if ($this->jQuery()->isEnabled()) {
//    $this->jQuery()->setLocalPath('lib/jquery-ui-1.8.14/js/jquery-1.5.1.min.js');
//    if ($this->jQuery()->uiIsEnabled()) {
//        $this->jQuery()->setUiLocalPath('lib/jquery-ui-1.8.14/js/jquery-ui-1.8.14.custom.min.js')
//                ->addStylesheet('lib/jquery-ui-1.8.14/css/pepper-grinder/jquery-ui-1.8.14.custom.css');
//    }
//}
// Set dojo library
//if ($this->dojo()->isEnabled()) {
//    Zend_Dojo_View_Helper_Dojo::setUseDeclarative();
//    $this->dojo()->setDjConfigOption('usePlainJson', TRUE)
//            ->setLocalPath('lib/dojo-release-1.6.1/dojo/dojo.js')
//            ->addStyleSheetModule('dijit.themes.tundra');
//}
?>
<?php echo $this->doctype() . PHP_EOL; ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php
        echo $this->headMeta() . PHP_EOL;
        echo $this->headTitle() . PHP_EOL;
        echo $this->headLink() . PHP_EOL;
        echo $this->headStyle() . PHP_EOL;
        echo $this->headScript() . PHP_EOL;
//        if ($this->jQuery()->isEnabled()) {
//            echo $this->jQuery() . PHP_EOL;
//        }
//        if ($this->dojo()->isEnabled()) {
//            echo $this->dojo() . PHP_EOL;
//        }
//        echo $this->headScript();
        ?>
    </head>
    <body>
        <div id="header">
            <?php echo $this->render('html/_banner.phtml'); ?>
            <div class="menu">
                <?php //echo $this->render('html/_menu.phtml');   ?>
                <div id="time"></div>
            </div>
        </div>
        <div id="main">
            <div id="content">
                <?php echo $this->layout()->content; ?>
            </div>
            <div class="fix"></div>
        </div>
        <div id="footer">
            <?php echo $this->render('html/_footer.phtml'); ?>
        </div>
    </body>
</html>
