<table id="jqGridTest" style="display:none"></table>

<script type="text/javascript">
    $(document).ready(function(){
        function add_record() { window.location='/front/test/add'; }
    
        function delete_record(command,grid)
        {
            var record_count = $('.trSelected',grid).length;
            if (0 == record_count)
            {
                alert('Please select a record first by clicking on the appropriate row.');
                return;
            }
            $('.trSelected',grid).each(function(){
                var id = this.id.substr(3);
                window.location = '/user/delete/id/'+id;
            });
        } // delete_record

        function edit_record(command,grid)
        {
            var record_count = $('.trSelected',grid).length;
            if (0 == record_count)
            {
                alert('Select a record first by clicking on the appropriate row.');
                return;
            }
            $('.trSelected',grid).each(function(){
                var id = this.id.substr(3);
                window.location = '/user/edit/id/'+id;
            });
        } // edit_record

        $('#jqGirdTest').flexigrid({
            url: "http:\/\/localhost\/QLTSv1\/front\/test\/records\/index.php",
            dataType: "json",
            buttons: [
                {name: 'Add', bclass: 'add', onpress: add_record},
                {name: 'Edit', bclass: 'edit', onpress: edit_record},
                {name: 'Delete', bclass: 'delete', onpress: delete_record}
            ],
            colModel: [
                {display: 'Ma_tai_san', name: 'Ma_tai_san', width: 30, sortable: true, align: 'left'},
                {display: 'UserID', name: 'UserID', width: 30, sortable: true, align: 'left'},
                {display: 'Detail', name: 'Detail', width: 150, sortable: false, align: 'left'},
                {display: 'Date', name: 'Date', width: 30, sortable: true, align: 'left'}
            
            ],
            searchitems : [
                {display: 'Ma_tai_san', name : 'Ma_tai_san'},
                {display: 'UserID', name : 'UserID', isdefault: true}
            ],
            sortname: "Ma_tai_san",
            sortorder: "asc",
            usepager: true,
            title: 'Loan Table',
            useRp: true,
            rp: 10,
            width: 700,
            height: 200
        });
    });
</script>

