<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headLink(); ?>   
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>   
    </head>

    <body>
        <h1> User Default Template</h1>
        <?php echo $this->layout()->content; ?>
    </body>
</html>