<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
<form id="form1" name="form1" method="post" action="">
  <table width="50%" align="center">
    <tr>
      <td colspan="2">Item ID</td>
      <td width="2%">:</td>
      <td width="52%"><label for="itemID"></label>
      <input type="text" name="itemID" id="itemID" /></td>
    </tr>
    <tr>
      <td colspan="2">User ID</td>
      <td>:</td>
      <td><label for="userid"></label>
      <input type="text" name="userID" id="userID" /></td>
    </tr>
    <tr>
      <td colspan="2">Detail</td>
      <td>:</td>
      <td><label for="detail"></label>
      <input type="text" name="detail" id="detail" /></td>
    </tr>
    <tr>
      <td colspan="2">Curtime</td>
      <td>:</td>
      <td><label for="curtime"></label>
      <input type="text" name="curtime" id="curtime" /></td>
    </tr>
    <tr>
      <td width="10%"><input type="submit" name="add" id="add" value="ADD" /></td>
      <td width="10%"><input type="reset" name="reset" id="reset" value="Reset" /></td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
  </table>
</form>
</body>
</html>