<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><!-- InstanceBegin template="/Templates/SkillsGroup_HRM.dwt" codeOutsideHTMLIsLocked="false" -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!-- InstanceBeginEditable name="title" -->
<title>Untitled Document</title>
<!-- InstanceEndEditable -->
<meta name="keywords" content="SkillsGroup's HRM" />
<meta name="description" content="SkillsGroup's HRM" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="../images/styles/reset1.css" rel="stylesheet" type="text/css" media="screen" />
<link href="../images/styles/global.css" rel="stylesheet" type="text/css" media="screen" />
<script type="text/javascript" src="../js/jquery-1.js"></script>
<script type="text/javascript" src="../js/jquery.js"></script>
<!-- InstanceBeginEditable name="head" -->
		<script type="text/javascript" language="javascript" src="../js/jquery.js"></script>
		<script type="text/javascript" language="javascript" src="../js/jquery.dataTables.js"></script>
		<script type="text/javascript" charset="utf-8">
			var oTable;
			
			$(document).ready(function() {
				$('#form').submit( function() {
					var sData = $('input', oTable.fnGetNodes()).serialize();
					alert( "The following data would have been submitted to the server: \n\n"+sData );
					return false;
				} );
				
				oTable = $('#example').dataTable();
			} );
		</script>
<!-- InstanceEndEditable -->

<link href="../images/styles/sIFR-screen.css" rel="stylesheet" type="text/css" media="screen" />
</head>

<body>

<script type="text/javascript" language="javascript">

 function hoverthis(elementID,state) {
	 if(state==0) {
		 elementID.className = "hover";
	 } else if(state==1) {
		 elementID.className="even";
	 } else {
	 	 elementID.className="odd";
	 }
}

</script>
<script language="javascript">
	function windowDimensions() {
		if (document.compatMode && document.compatMode != "BackCompat") {
			x = document.documentElement.clientWidth;
		} else {
			x = document.body.clientWidth;
		}
		y = document.body.clientHeight;
	
		return [x,y];
	}
	function exploitSpace() {
		dimensions = windowDimensions();
	
		if (document.getElementById("rightMenu")) {
			document.getElementById("rightMenu").height = dimensions[1]-130;
		}
	
		if (document.getElementById("rightMenuHolder")) {
			document.getElementById("rightMenuHolder").width = dimensions[0]-200;
		}
	}
	
	exploitSpace();
	window.onresize = exploitSpace;
</script>
<script type="text/javascript">
<!--
	function doHandleAll() {
			with (document.form1) {
				if(elements['allCheck'].checked == false){
					doUnCheckAll();
				}
				else if(elements['allCheck'].checked == true){
					doCheckAll();
				}
			}
		}
	
		function doCheckAll() {
			with (document.form1) {
				for (var i=0; i < elements.length; i++) {
					if (elements[i].type == 'checkbox') {
						elements[i].checked = true;
					}
				}
			}
		}
	
		function doUnCheckAll() {
			with (document.form1) {
				for (var i=0; i < elements.length; i++) {
					if (elements[i].type == 'checkbox') {
						elements[i].checked = false;
					}
				}
			}
		}
-->					
</script>
<table id="banner" cellpadding="0" cellspacing="0" border="0">
<tbody>
<tr>
    <td>
    <div class="mauser">
        Welcome, <span style="font-weight:bold">Admin</span> <span style="color:#333333">[ <a href="/">Change Password</a> , <a href="login.html">Sign Out</a> ]</span>
    </div>
    </td>
</tr>
<tr>
    <td>
    	<h2 style="font-size:260%;font-weight:bold;color:#fff;padding-left:60px">SkillsGroup's HRM</h2>
    </td>
</tr>
<tr>
    <td>
    	<span style="color:#fff;padding-left:250px;">Developed by Group 40</span>
    </td>
</tr>
</tbody>
<!--/#banner-->

</table>
<table id="navbar" cellpadding="0" cellspacing="0" border="0">
    <tbody>
        <tr>
            <td width="200">
            	<div id="ticker">
                    <ul>
                        <li>
                          <div id="newsticker" class="clearfix"> 
                            <ul class="newsticker" id="newslist" style="text-align:left;">
                              <li><img src="../images/assets/arrow_na.png" alt="" /></li>
                              <li style="display: none;"><img src="../images/assets/arrow_na.png" alt="" /></li>
                            </ul>
                          </div>
                          <!--/#newsticker-->
                        </li>
                        <li><a></a></li>
                    </ul>
                </div>
            <script type="text/javascript">
            <!--
                 $("#newslist").newsticker(1);
            -->
            </script>
            </td>
            <td>
                <div id="navi">
                    <ul>
                    	<li><a href="home.html">Home</a></li>
                        <li><a href="organization.html">Organization</a></li>
                        <li><a href="m_employee.html">Employee</a></li>
                        <li><a href="#">Labor-Contract</a></li>
                        <li><a href="salary_timekeeping.html">Salary</a></li>
                        <li><a href="#">Reports</a></li>
                        <li class="last"><a href="m_user.html">System</a></li>
                    </ul>
                </div>
            </td>
        </tr>
    </tbody>
</table>
<!--/#navbar-->
<div id="wrap-body">
    <div id="leftside">
      <div id="navleft">
          <div class="navleft"><!-- InstanceBeginEditable name="navleft" -->Salary<!-- InstanceEndEditable --></div>
                        <!-- InstanceBeginEditable name="ul" -->
                            <ul>
                                <li><a href="salary_timekeeping.html">Timekeeping</a></li>
                                <li><a href="salary_setup.html">Setup Salary</a></li>
                                <li><a href="salary_calculate.html">Calculate Salary</a></li>
                            </ul>
						<!-- InstanceEndEditable --></div>
                    <!--/#leftside-->
    </div>
    <!--/#left-bar-->
    
    <div id="rightside">
        <div id="pageContent"><!-- InstanceBeginEditable name="pageContent" -->
            <form action="/" method="post" name="form1" id="form">
            	<div class="head">
                    <div class="line" style="border-bottom:1px solid #aaaaaa;">
                        <h2>Setup Salary</h2>
                    </div>
                	<div class="line" style="line-height:1px;">
                    	<a href="salary_setup_add.html"><input type="image" onmouseover="this.src='../images/assets/btn_add_hover.png';" onmouseout="this.src='../images/assets/btn_add.png';"  style="border: medium none;" src="../images/assets/btn_add.png" alt="Add" title="Add" name="submit"/></a>
                        <input type="image" onmouseover="this.src='../images/assets/btn_delete_hover.png';" onmouseout="this.src='../images/assets/btn_delete.png';"  style="border: medium none;" src="../images/assets/btn_delete.png" alt="Delete" title="Delete" name="submit"/>
                    </div>
                	<div class="line">
                    	<h3>Search</h3>
                    </div>
                </div>
                <!--/.head-->
                
                <div class="roundbox">
                    <div class="n" style="width:100%">
                    <div class="e">
                    <div class="s">
                    <div class="w">
                    <div class="nw">
                    <div class="ne">
                    <div class="se">
                    <div class="sw" style="padding:20px">
                        <div class="tbl" style="background-color:#e5e5e5">
                        	<table class="listing" cellspacing="1" cellpadding="5" border="0" width="100%" id="example">
                            	<col style="width:5%;" />
                                <col style="width:15%;" />
                                <col style="width:30%"/>
                                <col style="width:30%"/>
                                <col style="width:20%"/>
                            	<tbody>
                                <tr>
                                	<td colspan="5">
                                    	<div class="border1"></div>
                                    </td>
                                </tr>
                                <tr class="tblHeader">
                                    <td class="chk">
                                        <input class="checkbox" type="checkbox" onclick="doHandleAll();" value="" name="allCheck"/>
                                    </td>
                                    <td class="dataLabel">
                                        Employee
                                    </td>
                                    <td class="dataLabel">
                                        Basic salary
                                    </td>
                                    <td class="dataLabel">
                                        Total salary
                                    </td>
                                    <td class="dataLabel">
                                        Texable Income
                                    </td>
                                </tr>
                                <tr>
                                	<td colspan="5" width="100%">
                                    	<div class="border1"></div>
                                    </td>
                                </tr>
                                <tr class="odd" onmouseout="hoverthis(this,2)" onmouseover="hoverthis(this,0);">
                                    <td class="chk">
                                        <input class="checkbox" type="checkbox" value="" name="chkLogID"/>
                                    </td>
                                    <td>
                                        <a href="salary_setup_edit.html">Employee 001</a>
                                    </td>
                                    <td>
                                        <a href="salary_setup_edit.html">Basic salary 001</a>
                                    </td>
                                    <td>
                                        <a href="salary_setup_edit.html">Total salary 001</a>
                                    </td>
                                    <td>
                                        <a href="salary_setup_edit.html">Texable Income 001</a>
                                    </td>
                                </tr>
                                <tr class="even" onmouseout="hoverthis(this,1)" onmouseover="hoverthis(this,0);">
                                    <td class="chk">
                                        <input class="checkbox" type="checkbox" value="" name="chkLogID"/>
                                    </td>
                                    <td>
                                        <a href="salary_setup_edit.html">Employee 002</a>
                                    </td>
                                    <td>
                                        <a href="salary_setup_edit.html">Basic salary 002</a>
                                    </td>
                                    <td>
                                        <a href="salary_setup_edit.html">Total salary 002</a>
                                    </td>
                                    <td>
                                        <a href="salary_setup_edit.html">Texable Income 002</a>
                                    </td>
                                </tr>
                                <tr class="odd" onmouseout="hoverthis(this,2)" onmouseover="hoverthis(this,0);">
                                    <td class="chk">
                                        <input class="checkbox" type="checkbox" value="" name="chkLogID"/>
                                    </td>
                                    <td>
                                        <a href="salary_setup_edit.html">Employee 003</a>
                                    </td>
                                    <td>
                                        <a href="salary_setup_edit.html">Basic salary 003</a>
                                    </td>
                                    <td>
                                        <a href="salary_setup_edit.html">Total salary 003</a>
                                    </td>
                                    <td>
                                        <a href="salary_setup_edit.html">Texable Income 003</a>
                                    </td>
                                </tr>
                                <tr class="even" onmouseout="hoverthis(this,1)" onmouseover="hoverthis(this,0);">
                                    <td class="chk">
                                        <input class="checkbox" type="checkbox" value="" name="chkLogID"/>
                                    </td>
                                    <td>
                                        <a href="salary_setup_edit.html">Employee 004</a>
                                    </td>
                                    <td>
                                        <a href="salary_setup_edit.html">Basic salary 004</a>
                                    </td>
                                    <td>
                                        <a href="salary_setup_edit.html">Total salary 004</a>
                                    </td>
                                    <td>
                                        <a href="salary_setup_edit.html">Texable Income 004</a>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    </div>
                    </div>
                    </div>
                    </div>
                    </div>
                    </div>
                    </div>
            </div>
            <!--/.roundbox-->
            </form>
		<!-- InstanceEndEditable -->
        </div>
        <!--/#pageContent-->
    </div>
    <!--/#rightside-->
</div>
<!--/#wrap-body-->
</body>
<!-- InstanceEnd --></html>
