<?php
/**
 * File layout.phtml
 * 
 * @versoin 1.0
 * @author OanhNN
 * 
 * @todo layout of application
 */
// Set title
$this->headTitle()->append($this->translate('QLTS v1'));
$this->headTitle()->setSeparator(' :: ');
$this->headTitle()->append($this->pagetitle);
$this->jQuery()->enable()->uiEnable();
//$this->jQuery()->uiEnable();
if ($this->jQuery()->uiIsEnabled()) {
    $this->jQuery()->setUiLocalPath($this->baseUrl() . '/lib/jquery-ui-1.8.14/js/jquery-ui-1.8.14.custom.min.js')
            ->addStyleSheet($this->baseUrl() . '/lib/jquery-ui-1.8.14/css/ui-lightness/jquery-ui-1.8.14.custom.css');
}

$this->userInfo = Zend_Auth::getInstance()->getIdentity();
?>
<?php echo $this->doctype() . PHP_EOL; ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php
        echo $this->headMeta() . PHP_EOL;
        echo $this->headTitle() . PHP_EOL;
        if ($this->jQuery()->isEnabled()) {
            echo $this->jQuery() . PHP_EOL;
        }
        echo $this->headLink() . PHP_EOL;
        echo $this->headStyle() . PHP_EOL;
        echo $this->headScript() . PHP_EOL;
        ?>
    </head>
    <body>
        <div>
            <?php echo $this->render('html/_banner.phtml'); ?>
        </div> <!-- end of banner -->
        <div>
            <?php echo $this->render('html/_navbar.phtml'); ?>
        </div> <!--end of navbar -->
        <div id="wrap-body">
            <div id="leftside">
                <?php echo $this->render('html/_leftbar.phtml'); ?>
            </div><!-- end of leftside-->
            <div id="rightside">
                <div id="pageContent">
                    <h2 style="font-size: 18px; margin: 15px;"><?php echo $this->pagetitle; ?></h2>
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
        </div>
        <div class="fix"></div>
        <div id="footer">
            <?php echo $this->render('html/_footer.phtml'); ?>
        </div>
    </body>
</html>
