<?php
/**
 * File login.phtml
 * 
 * @versoin 1.0
 * @author OanhNN
 * 
 * @todo layout of login page
 */

// Set title
$this->headTitle()->append($this->translate('QLTS v1'));
$this->headTitle()->setSeparator(' :: ');
$this->headTitle()->append($this->pagetitle);

//$this->jQuery()->uiEnable();
if ($this->jQuery()->uiIsEnabled()) {
    $this->jQuery()->setUiLocalPath($this->baseUrl() . '/lib/jquery-ui-1.8.14/js/jquery-ui-1.8.14.custom.min.js')
            ->addStyleSheet($this->baseUrl() . '/lib/jquery-ui-1.8.14/css/ui-lightness/jquery-ui-1.8.14.custom.css');
}
?>
<?php echo $this->doctype() . PHP_EOL; ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php
        echo $this->headMeta() . PHP_EOL;
        echo $this->headTitle() . PHP_EOL;
        echo $this->headLink() . PHP_EOL;
        echo $this->headStyle() . PHP_EOL;
        echo $this->headScript() . PHP_EOL;
//        if ($this->jQuery()->isEnabled()) {
//            echo $this->jQuery() . PHP_EOL;
//        }
//        if ($this->dojo()->isEnabled()) {
//            echo $this->dojo() . PHP_EOL;
//        }
//        echo $this->headScript();
        ?>
    </head>
    <body id="login">
        <?php echo $this->layout()->content; ?>
    </body>
</html>