<?php
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<div id="navleft">
    <div class="navleft">Home</div>
    <?php
    if ($this->userInfo != NULL) {
        switch ($this->userInfo->Role) {
            case 0: // Super Admin
                ?>
                <ul id="sadminmenu">
                    <li><a href="<?php echo $this->url(array('module' => 'asset', 'controller' => 'message', 'action' => 'list')); ?>">Quản lý tin nhắn</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'user', 'action' => 'list')); ?>">Quản lý tài khoản</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'asset', 'controller' => 'request', 'action' => 'list')); ?>">Quản lý yêu cầu</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'asset', 'controller' => 'item', 'action' => 'list')); ?>">Quản lý tài sản</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'asset', 'controller' => 'loan', 'action' => 'list')); ?>">Quản lý cho mượn</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'asset', 'controller' => 'history', 'action' => 'list', 'mode' => 3)); ?>">Lịch sử bàn giao</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'asset', 'controller' => 'upgrade', 'action' => 'list')); ?>">Lịch sử nâng cấp</a></li>
                </ul>
                <?php
                break;
            case 1: // Admin
                ?>
                <ul>
                    <li><a href="<?php echo $this->url(array('module' => 'asset', 'controller' => 'message', 'action' => 'list')); ?>">Quản lý tin nhắn</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'asset', 'controller' => 'request', 'action' => 'list')); ?>">Quản lý yêu cầu</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'asset', 'controller' => 'item', 'action' => 'list')); ?>">Quản lý tài sản</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'asset', 'controller' => 'loan', 'action' => 'list')); ?>">Quản lý cho mượn</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'asset', 'controller' => 'history', 'action' => 'list', 'mode' => 3)); ?>">Lịch sử bàn giao</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'asset', 'controller' => 'upgrade', 'action' => 'list')); ?>">Lịch sử nâng cấp</a></li>
                </ul>
                <?php
                break;
            case 3: // IT
                ?>
                <ul>
                    <li><a href="<?php echo $this->url(array('module' => 'asset', 'controller' => 'message', 'action' => 'list')); ?>">Quản lý tin nhắn</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'asset', 'controller' => 'request', 'action' => 'list')); ?>">Quản lý yêu cầu</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'asset', 'controller' => 'item', 'action' => 'list')); ?>">Quản lý tài sản</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'asset', 'controller' => 'history', 'action' => 'list', 'mode' => 3)); ?>">Lịch sử bàn giao</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'asset', 'controller' => 'upgrade', 'action' => 'list')); ?>">Lịch sử nâng cấp</a></li>
                </ul>
                <?php
                break;
            case 2: // User
            default : // Other
                ?>
                <ul>
                    <li><a href="<?php echo $this->url(array('module' => 'asset', 'controller' => 'message', 'action' => 'list')); ?>">Quản lý tin nhắn</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'asset', 'controller' => 'request', 'action' => 'list')); ?>">Quản lý yêu cầu</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'asset', 'controller' => 'item', 'action' => 'list')); ?>">Quản lý tài sản</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'asset', 'controller' => 'history', 'action' => 'list', 'mode' => 3)); ?>">Lịch sử bàn giao</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'asset', 'controller' => 'upgrade', 'action' => 'list')); ?>">Lịch sử nâng cấp</a></li>
                </ul>
                <?php
                break;
        }
    }
    ?>

</div>