<table id="navbar" cellpadding="0" cellspacing="0" border="0">
    <tbody>
        <tr>
            <td width="200">
                <div id="ticker">
                    <ul>
                        <li>
                            <div id="newsticker" class="clearfix"> 
                                <ul class="newsticker" id="newslist" style="text-align:left;">
                                    <li><img src="<?php echo $this->templateUrl . 'images/arrow_na.png'; ?>" alt="" /></li>
                                    <li style="display: none;"><img src="<?php echo $this->templateUrl . 'images/arrow_na.png'; ?>" alt="" /></li>
                                </ul>
                            </div>
                            <!--/#newsticker-->
                        </li>
                        <li><a></a></li>
                    </ul>
                </div>
            </td>
            <td>
                <div id="navi">
                    <ul>
                        <li><a href="<?php echo $this->url(array('module' => 'front', 'controller' => 'index', 'action' => 'index')); ?>">Home</a></li>
                        <li><a href="<?php echo $this->url(array('module' => 'front', 'controller' => 'mail', 'action' => 'index')); ?>" >Contact</a></li>
                        <li class="last"><a href="<?php echo $this->url(array('module' => 'front', 'controller' => 'index', 'action' => 'about')); ?>">About us</a></li>
                    </ul>
                </div>
            </td>
        </tr>
    </tbody>
</table>
<!--/#navbar-->