<?php
/**
 * File layout.phtml
 * 
 * @versoin 1.0
 * @author OanhNN
 * 
 * @todo layout of application
 */
// templateUrl
$this->templateUrl = $this->baseUrl() . '/templates/' . TEMPLATE_NAME . '/';

// Set encoding
$this->setEncoding('UTF-8');

// Set doctype
$this->doctype('XHTML1_STRICT');

// Set meta
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
$this->headMeta()->appendHttpEquiv('Content-Language', 'vi-VN');

// Set title
$this->headTitle()->append($this->translate('PAGE_TITLE'));
$this->headTitle()->setSeparator(' :: ');
$this->headTitle()->append($this->pagetitle);

// Set favicon
$this->headLink(array('rel' => 'shortcut icon', 'href' => $this->baseUrl() . '/favicon.ico', 'type' => 'image/x-icon'), 'append');

// Set css style
$this->headLink()->prependStylesheet($this->templateUrl . 'css/style.css', 'screen');
// fix css for IE8 or LOWER
$this->headLink()->appendStylesheet($this->templateUrl . 'css/style-ie8.css', 'screen', 'lte IE 8');

// Set js script
//$this->headScript()->prependFile($this->baseUrl() . '/lib/jquery-ui-1.8.14/js/jquery-1.5.1.min.js');

$this->addHelperPath('ZendX/JQuery/View/Helper', 'ZendX_JQuery_View_Helper');
//$this->addHelperPath('Ingot/JQuery/JqGrid/View/Helper','Ingot_JQuery_JqGrid_View_Helper');
$viewRenderer = new Zend_Controller_Action_Helper_ViewRenderer ();
$viewRenderer->setView($this);

$this->jQuery()->setLocalPath($this->baseUrl() . '/lib/jquery-ui-1.8.14/js/jquery-1.5.1.min.js')
        ->enable();
$this->jQuery()->uiEnable();
if ($this->jQuery()->uiIsEnabled()) {
    $this->jQuery()->setUiLocalPath($this->baseUrl() . '/lib/jquery-ui-1.8.14/js/jquery-ui-1.8.14.custom.min.js')
            ->addStyleSheet($this->baseUrl() . '/lib/jquery-ui-1.8.14/css/pepper-grinder/jquery-ui-1.8.14.custom.css');
}

$this->userInfo = Zend_Auth::getInstance()->getIdentity();
?>
<?php echo $this->doctype() . PHP_EOL; ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php
        echo $this->headMeta() . PHP_EOL;
        echo $this->headTitle() . PHP_EOL;
        echo $this->headLink() . PHP_EOL;
        echo $this->headStyle() . PHP_EOL;
        echo $this->headScript() . PHP_EOL;
        if ($this->jQuery()->isEnabled()) {
            echo $this->jQuery() . PHP_EOL;
        }
        ?>
    </head>
    <body>
        <div>
            <?php echo $this->render('html/_banner.phtml'); ?>
        </div>
        <div>
            <?php echo $this->render('html/_navbar.phtml'); ?>
        </div>
        <!--/#banner-->
        <div id="wrap-body">
            <div id="leftside">
                <?php echo $this->render('html/_leftbar.phtml'); ?>
            </div>
            <!--/#leftside-->
            <div id="rightside">
                <div id="pageContent">
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
        </div>
        <div class="fix"></div>
        <div id="footer">
            <?php echo $this->render('html/_footer.phtml'); ?>
        </div>
    </body>
</html>
